phrases = [
    "Detect the object",
    "Detect this item",
    "Identify the object",
    "Find what's here",
    "Locate the item",
    "Spot the object",
    "Pinpoint this thing",
    "Discover the object",
    "Recognize this item",
    "Identify what's here",
    "Spot what's in front",
    "Locate the item in view",
    "Pinpoint this object",
    "Detect and identify",
    "Recognize and locate",
    "Identify this",
    "What is this",
    "What am I seeing",
    "What object is here",
    "What's in front of me",
    "Can you identify this",
    "What's this in front of me",
    "Identify the object in view",
    "Detect and recognize this",
    "Identify what's in front",
    "What am I holding",
    "What object am I looking at",
    "What's in my hand",
    "What is in front of me",
    "Can you detect this item",
    "Can you recognize this",
    "Can you identify what's here",
    "Tell me what this is",
    "Tell me what I'm seeing",
    "Figure out what this is",
    "Recognize the object in view",
    "Identify what's in my hand",
    "What is this in the image",
    "What am I holding up",
    "What object is in front of me",
    "Detect the object in the picture",
    "Recognize this object here",
    "Identify what I'm looking at",
    "What's the object in this scene",
    "Detect and identify this item",
    "Recognize the object in the photo",
    "Identify what's in this image",
    "What am I pointing at",
    "What's this thing in the photo"
]
phrases_about_object = [
    "Tell me about the object",
    "Tell me something about this item",
    "Describe the object",
    "Give me details about this",
    "What can you tell me about this",
    "Inform me about the object",
    "What's the information about this",
    "Explain this object to me",
    "Describe what you see here",
    "What is this and its details",
    "Why is this object important",
    "Why is this used",
    "What's the significance of this",
    "Elaborate on this object",
    "Provide details about this",
    "Why is it used",
    "What is this",
    "What's this all about",
    "Can you give me some details",
    "Can you describe this",
    "What do you know about this",
    "What is the purpose of this",
    "Tell me about this thing",
    "Inform me about this item",
    "Why is this object here",
    "Give me some insights about this",
    "What's the function of this",
    "Tell me something about this object",
    "Why is this object significant"
]
